name: flutter_mentions
description: A simple flutter input widget to add @ mentions functionality to your app.
version: 2.0.1
homepage: https://github.com/fayeed/flutter_mentions

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_portal: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  